/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BencanaRouteImport } from './routes/bencana'
import { Route as DisabilitasRouteImport } from './routes/disabilitas'
import { Route as DownloadDataRouteImport } from './routes/download-data'
import { Route as EkonomiRouteImport } from './routes/ekonomi'
import { Route as GiziRouteImport } from './routes/gizi'
import { Route as KeluargaRouteImport } from './routes/keluarga'
import { Route as KependudukanRouteImport } from './routes/kependudukan'
import { Route as KesehatanRouteImport } from './routes/kesehatan'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as PendidikanRouteImport } from './routes/pendidikan'
import { Route as PetaTematikRouteImport } from './routes/peta-tematik'
import { Route as ProfilDesaRouteImport } from './routes/profil-desa'
import { Route as PublikasiRouteImport } from './routes/publikasi'
import { Route as UmkmRouteImport } from './routes/umkm'
import { Route as ApiPublicSyncSheetRouteImport } from './routes/api/public/sync/sheet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BencanaRoute = BencanaRouteImport.update({
  id: '/bencana',
  path: '/bencana',
  getParentRoute: () => rootRouteImport,
} as any)
const DisabilitasRoute = DisabilitasRouteImport.update({
  id: '/disabilitas',
  path: '/disabilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadDataRoute = DownloadDataRouteImport.update({
  id: '/download-data',
  path: '/download-data',
  getParentRoute: () => rootRouteImport,
} as any)
const EkonomiRoute = EkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const GiziRoute = GiziRouteImport.update({
  id: '/gizi',
  path: '/gizi',
  getParentRoute: () => rootRouteImport,
} as any)
const KeluargaRoute = KeluargaRouteImport.update({
  id: '/keluarga',
  path: '/keluarga',
  getParentRoute: () => rootRouteImport,
} as any)
const KependudukanRoute = KependudukanRouteImport.update({
  id: '/kependudukan',
  path: '/kependudukan',
  getParentRoute: () => rootRouteImport,
} as any)
const KesehatanRoute = KesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const PendidikanRoute = PendidikanRouteImport.update({
  id: '/pendidikan',
  path: '/pendidikan',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaTematikRoute = PetaTematikRouteImport.update({
  id: '/peta-tematik',
  path: '/peta-tematik',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilDesaRoute = ProfilDesaRouteImport.update({
  id: '/profil-desa',
  path: '/profil-desa',
  getParentRoute: () => rootRouteImport,
} as any)
const PublikasiRoute = PublikasiRouteImport.update({
  id: '/publikasi',
  path: '/publikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const UmkmRoute = UmkmRouteImport.update({
  id: '/umkm',
  path: '/umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncSheetRoute = ApiPublicSyncSheetRouteImport.update({
  id: '/api/public/sync/sheet',
  path: '/api/public/sync/sheet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bencana': typeof BencanaRoute
  '/disabilitas': typeof DisabilitasRoute
  '/download-data': typeof DownloadDataRoute
  '/ekonomi': typeof EkonomiRoute
  '/gizi': typeof GiziRoute
  '/keluarga': typeof KeluargaRoute
  '/kependudukan': typeof KependudukanRoute
  '/kesehatan': typeof KesehatanRoute
  '/metadata': typeof MetadataRoute
  '/pendidikan': typeof PendidikanRoute
  '/peta-tematik': typeof PetaTematikRoute
  '/profil-desa': typeof ProfilDesaRoute
  '/publikasi': typeof PublikasiRoute
  '/umkm': typeof UmkmRoute
  '/api/public/sync/sheet': typeof ApiPublicSyncSheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bencana': typeof BencanaRoute
  '/disabilitas': typeof DisabilitasRoute
  '/download-data': typeof DownloadDataRoute
  '/ekonomi': typeof EkonomiRoute
  '/gizi': typeof GiziRoute
  '/keluarga': typeof KeluargaRoute
  '/kependudukan': typeof KependudukanRoute
  '/kesehatan': typeof KesehatanRoute
  '/metadata': typeof MetadataRoute
  '/pendidikan': typeof PendidikanRoute
  '/peta-tematik': typeof PetaTematikRoute
  '/profil-desa': typeof ProfilDesaRoute
  '/publikasi': typeof PublikasiRoute
  '/umkm': typeof UmkmRoute
  '/api/public/sync/sheet': typeof ApiPublicSyncSheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bencana': typeof BencanaRoute
  '/disabilitas': typeof DisabilitasRoute
  '/download-data': typeof DownloadDataRoute
  '/ekonomi': typeof EkonomiRoute
  '/gizi': typeof GiziRoute
  '/keluarga': typeof KeluargaRoute
  '/kependudukan': typeof KependudukanRoute
  '/kesehatan': typeof KesehatanRoute
  '/metadata': typeof MetadataRoute
  '/pendidikan': typeof PendidikanRoute
  '/peta-tematik': typeof PetaTematikRoute
  '/profil-desa': typeof ProfilDesaRoute
  '/publikasi': typeof PublikasiRoute
  '/umkm': typeof UmkmRoute
  '/api/public/sync/sheet': typeof ApiPublicSyncSheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bencana'
    | '/disabilitas'
    | '/download-data'
    | '/ekonomi'
    | '/gizi'
    | '/keluarga'
    | '/kependudukan'
    | '/kesehatan'
    | '/metadata'
    | '/pendidikan'
    | '/peta-tematik'
    | '/profil-desa'
    | '/publikasi'
    | '/umkm'
    | '/api/public/sync/sheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bencana'
    | '/disabilitas'
    | '/download-data'
    | '/ekonomi'
    | '/gizi'
    | '/keluarga'
    | '/kependudukan'
    | '/kesehatan'
    | '/metadata'
    | '/pendidikan'
    | '/peta-tematik'
    | '/profil-desa'
    | '/publikasi'
    | '/umkm'
    | '/api/public/sync/sheet'
  id:
    | '__root__'
    | '/'
    | '/bencana'
    | '/disabilitas'
    | '/download-data'
    | '/ekonomi'
    | '/gizi'
    | '/keluarga'
    | '/kependudukan'
    | '/kesehatan'
    | '/metadata'
    | '/pendidikan'
    | '/peta-tematik'
    | '/profil-desa'
    | '/publikasi'
    | '/umkm'
    | '/api/public/sync/sheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BencanaRoute: typeof BencanaRoute
  DisabilitasRoute: typeof DisabilitasRoute
  DownloadDataRoute: typeof DownloadDataRoute
  EkonomiRoute: typeof EkonomiRoute
  GiziRoute: typeof GiziRoute
  KeluargaRoute: typeof KeluargaRoute
  KependudukanRoute: typeof KependudukanRoute
  KesehatanRoute: typeof KesehatanRoute
  MetadataRoute: typeof MetadataRoute
  PendidikanRoute: typeof PendidikanRoute
  PetaTematikRoute: typeof PetaTematikRoute
  ProfilDesaRoute: typeof ProfilDesaRoute
  PublikasiRoute: typeof PublikasiRoute
  UmkmRoute: typeof UmkmRoute
  ApiPublicSyncSheetRoute: typeof ApiPublicSyncSheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bencana': {
      id: '/bencana'
      path: '/bencana'
      fullPath: '/bencana'
      preLoaderRoute: typeof BencanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disabilitas': {
      id: '/disabilitas'
      path: '/disabilitas'
      fullPath: '/disabilitas'
      preLoaderRoute: typeof DisabilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-data': {
      id: '/download-data'
      path: '/download-data'
      fullPath: '/download-data'
      preLoaderRoute: typeof DownloadDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekonomi': {
      id: '/ekonomi'
      path: '/ekonomi'
      fullPath: '/ekonomi'
      preLoaderRoute: typeof EkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizi': {
      id: '/gizi'
      path: '/gizi'
      fullPath: '/gizi'
      preLoaderRoute: typeof GiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keluarga': {
      id: '/keluarga'
      path: '/keluarga'
      fullPath: '/keluarga'
      preLoaderRoute: typeof KeluargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kependudukan': {
      id: '/kependudukan'
      path: '/kependudukan'
      fullPath: '/kependudukan'
      preLoaderRoute: typeof KependudukanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesehatan': {
      id: '/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof KesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendidikan': {
      id: '/pendidikan'
      path: '/pendidikan'
      fullPath: '/pendidikan'
      preLoaderRoute: typeof PendidikanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta-tematik': {
      id: '/peta-tematik'
      path: '/peta-tematik'
      fullPath: '/peta-tematik'
      preLoaderRoute: typeof PetaTematikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-desa': {
      id: '/profil-desa'
      path: '/profil-desa'
      fullPath: '/profil-desa'
      preLoaderRoute: typeof ProfilDesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publikasi': {
      id: '/publikasi'
      path: '/publikasi'
      fullPath: '/publikasi'
      preLoaderRoute: typeof PublikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umkm': {
      id: '/umkm'
      path: '/umkm'
      fullPath: '/umkm'
      preLoaderRoute: typeof UmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/sheet': {
      id: '/api/public/sync/sheet'
      path: '/api/public/sync/sheet'
      fullPath: '/api/public/sync/sheet'
      preLoaderRoute: typeof ApiPublicSyncSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BencanaRoute: BencanaRoute,
  DisabilitasRoute: DisabilitasRoute,
  DownloadDataRoute: DownloadDataRoute,
  EkonomiRoute: EkonomiRoute,
  GiziRoute: GiziRoute,
  KeluargaRoute: KeluargaRoute,
  KependudukanRoute: KependudukanRoute,
  KesehatanRoute: KesehatanRoute,
  MetadataRoute: MetadataRoute,
  PendidikanRoute: PendidikanRoute,
  PetaTematikRoute: PetaTematikRoute,
  ProfilDesaRoute: ProfilDesaRoute,
  PublikasiRoute: PublikasiRoute,
  UmkmRoute: UmkmRoute,
  ApiPublicSyncSheetRoute: ApiPublicSyncSheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
